name: CI
on:
  - push
  - pull_request
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bash - Code Style
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHFMT_OPTS: -i 4
        with:
          sh_checker_shellcheck_disable: true
      - name: Python - Linting
        uses: astral-sh/ruff-action@v3
      - name: Python - Formatting
        run: ruff format --check
      - name: Python - Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Python - Dependencies
        run: pip install -r requirements.txt
      - name: OS Dependendencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fzf
          fzf --version
      - name: Python - Tests
        run: pytest
