name: CI
on:
  - push
  - pull_request
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bash - Code Style
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHFMT_OPTS: -i 4
        with:
          sh_checker_shellcheck_disable: true
      - name: Python - Linting
        uses: astral-sh/ruff-action@v3
      - name: Python - Formatting
        run: ruff format --check
